joint_limits:
  elbow_joint:
    has_acceleration_limits: true
    has_position_limits: true
    max_acceleration: 0.2
    max_position: 1.3962634015954636
    min_acceleration: 0.2
    min_position: 0.0
  shoulder_joint:
    has_acceleration_limits: true
    has_position_limits: true
    max_acceleration: 0.2
    max_position: 2.6179938779914944
    min_acceleration: 0.2
    min_position: 1.2217304763960306
  world_to_base:
    has_acceleration_limits: true
    has_position_limits: true
    max_acceleration: 0.2
    max_position: 2.9670597283903604
    min_acceleration: 0.2
    min_position: 0.3490658503988659
  wrist:
    has_acceleration_limits: true
    has_position_limits: true
    max_acceleration: 0.2
    max_position: 2.0943951023931953
    min_acceleration: 0.2
    min_position: 1.0471975511965976
