controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robot_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController
    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


robot_gripper_controller:
  ros__parameters:
    joint: hand_to_gripper_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - world_to_base
      - shoulder_joint
      - elbow_joint
      - wrist
robot_arm_controller:
  ros__parameters:
    joints:
      - world_to_base
      - shoulder_joint
      - elbow_joint
      - wrist
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
  